Neos:
  Flow:
    http:
      middlewares:
        'Sitegeist.OffCORS:CorsMiddleware':
          position: 'before session'
          middleware: 'Sitegeist\OffCORS\Middleware\CorsMiddleware'

Sitegeist:
  OffCORS:
    # allow credentials via cors (bool)
    allowCredentials: false
    # allowed cors origins (array or csv-string)
    allowedOrigins: "*"
    # allowed cors methods (array or csv-string)
    allowedMethods: "GET"
    # allowed cors headers (array or csv-string)
    allowedHeaders: ""
    # exposed cors headers (array or csv-string)
    exposedHeaders: ""
    # max age for cors informations (int)
    maxAge: 86400
